### ISSUE TITLE
Minor Incompatibility: "Arcanus: Continuum" 1.19.2

### ISSUE THREAD

**Issue by ElectroArtifex** [EvanoriMemoria/reincarnation-origins-phoenix#1]
Version: 1.19.2

When playing with both this mod and [Arcanus: Continuum](https://modrinth.com/mod/arcanus-continuum), the size changes do not apply to a phoenix origin player (neither ascended form slightly-small, nor rebirth form 1-block tall). 

Other origins mods that affect height work fine alongside it (ie: superior dwarf is still super tiny), so it seems to be this specific Origin mod. 

I have not tested this in the 1.20 versions of the mods, as the pack I found this error in was 1.19.2 only, and I understand if this mod is no longer supporting 1.19.2, but I wanted to make sure the issue was noted in case it persists between versions. I can also report this issue to Arcanus: Continuum if it will help get a dialogue going. 

Thanks so much for an amazing mod! I hope this can be resolved :)

**Comment by EvanoriMemoria** [comment]
Thanks for the report! I'll have time to look into this in the next couple of days. I'm happy to continue supporting 1.19 for the time being.

**Comment by EvanoriMemoria** [comment]
Fixed as of mod version 1.0.4.
